query (
  $main: Int!,
  $vns: Int!,
  $regal: Int!,
  $valmont: Int!
) {
  boards 
  (ids: [
    $main,
    $vns,
    $regal,
    $valmont
  ] )
  {
    id,
    name,
    columns {
      id,
      title,
      type,
      settings_str
    }
    items {
      id,
      name,
      column_values {
        id,
        type,
        value
      }
    }
  }
}
